### PR TITLE
allow newer pytorch versions to be installed st they do not break API

### PR DESCRIPTION
**Pull request by erip**
Currently users with pytorch >1.10 cannot install COMET. This PR loosens this restriction by setting the upper version to the next major version of PyTorch which should ensure no API breakage.

I'm not a poetry user but `poetry.lock` seems like it should be updated... but locks are automatically generated, aren't they?

### CODE REVIEW

**Comment by erip** [comment]
Note: #70 should probably land before this. Once that happens, I can refresh this PR and let CI run so we know nothing broke.

**Comment by ricardorei** [comment]
Thanks @erip!

When using poetry after updating the requirements in the pyproject.toml you have to run the `poetry update`. I can do that no worries.

**Comment by erip** [comment]
Ah, got it! FWIW, I'm using this fork with no issues on my end. Not a perfect guarantee that nothing is broken but I think as long as pytorch doesn't break their API, this should be OK.

**Comment by ricardorei** [comment]
yes I ran the tests locally to check if everything was running with the new pytorch version and everything seems fine.

Actually, this is something we need to improve on the current CI. On PR the CI should run the tests and not just check installation problems.

**Pull request merged**
